name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: |
          python -m pip install pylint
          pylint kraken_async_api
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - run: |
#          python -m pip install coverage
#          python -m coverage --run --branch -m unittest
#          python -m coverage report
