name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: python -m unittest

#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - run: |
#          python -m pip install pylint
#          python -m pylint kraken_async_api
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - run: |
#          python -m pip install coverage
#          python -m coverage --run --branch -m unittest
#          python -m coverage report
